- name: Install LEMP stack on Ubuntu 22.04
  hosts: all
  become: true
  tasks:
    - name: Update all packages to latest
      apt:
        name: "*"
        state: latest

    - name: Install Nginx
      apt:
        name: nginx
        state: present

    - name: Install MySQL Server
      apt:
        name: mysql-server
        state: present

    - name: Install PHP8.1-fpm 
      apt:
        name: "{{ item }}"
        state: present
        update_cache: yes
      loop:
          - php8.1-fpm
          - php8.1-mysql
          - php8.1

    - name: Start Nginx service
      service:
        name: nginx
        state: started
        enabled: yes

    - name: Start MySQL service
      service:
        name: mysql
        state: started
        enabled: yes

    - name: Start PHP-FPM service
      service:
        name: php8.1-fpm
        state: started
        enabled: yes

    - name: Adjust Nginx server block configuration
      copy:
        dest: /etc/nginx/sites-available/default
        mode: '0644'
        content: |
          server {
              listen 80 default_server;
              listen [::]:80 default_server;
              root /var/www/html;
              index index.php index.html index.htm index.nginx-debian.html;

              server_name _;

              location / {
                  try_files $uri $uri/ =404;
              }

              location ~ \.php$ {
                  include snippets/fastcgi-php.conf;
                  fastcgi_pass unix:/var/run/php/php8.1-fpm.sock;
                  fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
                  include fastcgi_params;
              }

              location ~ /\.ht {
                  deny all;
              }
          }
      notify:
        - Restart Nginx

    - name: Copy Index To Remote Machine
      copy:
        src: /home/ahmed/week8/index.php
        dest: /var/www/html
        mode: '0644'
    
    - name: Install Python for mysqldb
      apt:
        name: python3-mysqldb
        state: present
  
    - name: Create a new database with name 'viewsdb'
      community.mysql.mysql_db:
        name: viewsdb
        state: present
    
    - name: Create database user with name 'bob' and password '1234' with all database privileges
      community.mysql.mysql_user:
        name: bob
        password: 1234
        priv: '*.*:ALL'
        state: present
    
    - name: Install Firewalld
      apt:
        name: firewalld
        state: present

    - name: Start Firewalld service
      service:
        name: firewalld
        state: started
        enabled: yes
    
    - name: permit traffic in default zone for https service
      ansible.posix.firewalld:
        service: "{{ item }}"
        permanent: true
        state: enabled
        immediate: true
      loop:
          - http
          - https
          - ssh



  handlers:
    - name: Restart Nginx
      service:
        name: nginx
        state: restarted
